#!/usr/bin/env python
"""Rebuild index.html with proper UTF-8 encoding - preserving all features."""
import json, os

def main():
    # Read the line-by-line content already identified from original
    # We'll reconstruct based on the known structure with all features
    
    lines = []
    
    # Header
    lines.append('<!DOCTYPE html>')
    lines.append('<html lang="zh-CN">')
    lines.append('<head>')
    lines.append('<meta charset="UTF-8">')
    lines.append('<meta name="viewport" content="width=device-width, initial-scale=1.0">')
    lines.append('<title>悟道</title>')
    lines.append('<style>')
    lines.append('  body { margin: 0; overflow: hidden; background: #050810;')
    lines.append('    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;')
    lines.append('    color: #c8d0e0; }')
    lines.append('  * { box-sizing: border-box; }')
    lines.append('  #ui-overlay { position: fixed; top: 0; left: 0; width: 100%; height: 100%;')
    lines.append('    pointer-events: none; z-index: 10; }')
    lines.append('  #status-text { position: fixed; bottom: 40px; left: 50%; transform: translateX(-50%);')
    lines.append('    font-size: 14px; color: rgba(200,208,224,0.4);')
    lines.append('    letter-spacing: 2px; transition: opacity 0.3s; z-index: 20;')
    lines.append('    text-shadow: 0 0 20px rgba(100,180,255,0.15); }')
    lines.append('  #transcript { position: fixed; bottom: 80px; left: 50%; transform: translateX(-50%);')
    lines.append('    font-size: 16px; color: rgba(200,208,224,0.7); text-align: center;')
    lines.append('    max-width: 70%; z-index: 20;')
    lines.append('    text-shadow: 0 0 20px rgba(100,180,255,0.2);')
    lines.append('    white-space: nowrap; overflow: hidden; text-overflow: ellipsis; }')
    lines.append('  #menu { position: fixed; top: 16px; right: 24px; z-index: 20;')
    lines.append('    display: flex; gap: 20px; font-size: 14px;')
    lines.append('    color: rgba(200,208,224,0.5); letter-spacing: 1px; }')
    lines.append('  #menu span { cursor: pointer; transition: color 0.2s; }')
    lines.append('  #menu span:hover { color: rgba(200,208,224,0.9); }')
    lines.append('  .partial-text {')
    lines.append('    color: rgba(100,180,255,0.3);')
    lines.append('    border-right: 1px solid rgba(100,180,255,0.3);')
    lines.append('    animation: blink 0.8s step-end infinite;')
    lines.append('  }')
    lines.append('  @keyframes blink {')
    lines.append('    50% { border-color: transparent; }')
    lines.append('  }')
    lines.append('</style>')
    lines.append('</head>')
    lines.append('<body>')
    lines.append('<div id="ui-overlay">')
    lines.append('  <div id="menu"><span data-href="/">聊天</span><span data-href="/room">会议室</span><span data-href="/admin">管理</span><span data-href="/about">关于</span></div>')
    lines.append('</div>')
    lines.append('<div id="transcript"></div>')
    lines.append('<div id="status-text">空闲</div>')

    # Script tag with all JS
    lines.append('<script type="importmap">')
    lines.append('{')
    lines.append('  "imports": {')
    lines.append('    "three": "https://cdn.jsdelivr.net/npm/three@0.160.0/build/three.module.js",')
    lines.append('    "three/addons/": "https://cdn.jsdelivr.net/npm/three@0.160.0/examples/jsm/"')
    lines.append('  }')
    lines.append('}')
    lines.append('</script>')
    lines.append('<script type="module">')

    # JS code
    lines.append("import * as THREE from 'three';")
    lines.append("import { OrbitControls } from 'three/addons/controls/OrbitControls.js';")
    lines.append("import { EffectComposer } from 'three/addons/postprocessing/EffectComposer.js';")
    lines.append("import { RenderPass } from 'three/addons/postprocessing/RenderPass.js';")
    lines.append("import { UnrealBloomPass } from 'three/addons/postprocessing/UnrealBloomPass.js';")
    lines.append("")
    lines.append("// ---- Setup ----")
    lines.append("const scene = new THREE.Scene();")
    lines.append("scene.background = new THREE.Color('#050810');")
    lines.append("const camera = new THREE.PerspectiveCamera(60, window.innerWidth / window.innerHeight, 0.1, 100);")
    lines.append("camera.position.set(0, 0, 12);")
    lines.append("const renderer = new THREE.WebGLRenderer({ antialias: true });")
    lines.append("renderer.setSize(window.innerWidth, window.innerHeight);")
    lines.append("renderer.setPixelRatio(Math.min(window.devicePixelRatio, 2));")
    lines.append("renderer.toneMapping = THREE.ReinhardToneMapping;")
    lines.append("document.body.appendChild(renderer.domElement);")
    lines.append("")
    lines.append("// ---- Composer ----")
    lines.append("const composer = new EffectComposer(renderer);")
    lines.append("const renderPass = new RenderPass(scene, camera);")
    lines.append("composer.addPass(renderPass);")
    lines.append("const bloomPass = new UnrealBloomPass(new THREE.Vector2(window.innerWidth, window.innerHeight), 0.4, 0.3, 0.1);")
    lines.append("composer.addPass(bloomPass);")
    lines.append("")
    lines.append("// ---- Orbit Controls ----")
    lines.append("const controls = new OrbitControls(camera, renderer.domElement);")
    lines.append("controls.enableDamping = true;")
    lines.append("controls.dampingFactor = 0.08;")
    lines.append("controls.minDistance = 4;")
    lines.append("controls.maxDistance = 30;")
    lines.append("controls.autoRotate = false;")
    lines.append("controls.target.set(0, 0, 0);")
    lines.append("")
    lines.append("// ---- State Variables ----")
    lines.append("let wudaoState = 'idle';")
    lines.append("let speakIntensity = 0;")
    lines.append("let particleSpeed = 0.002;")
    lines.append("let tentacleWaveSpeed = 0.003;")
    lines.append("let bloomStrength = 0.4;")
    lines.append("")
    lines.append("// ---- Tentacle Particles ----")
    lines.append("const TENTACLE_COUNT = 7;")
    lines.append("const PARTICLES_PER_TENTACLE = 120;")
    lines.append("const tentacleGroups = [];")
    lines.append("const tentacleColors = [")
    lines.append("  new THREE.Color(0.3, 0.8, 1.0),")
    lines.append("  new THREE.Color(0.6, 0.4, 1.0),")
    lines.append("  new THREE.Color(0.2, 1.0, 0.6),")
    lines.append("  new THREE.Color(1.0, 0.5, 0.2),")
    lines.append("  new THREE.Color(0.8, 0.3, 0.9),")
    lines.append("  new THREE.Color(0.3, 0.6, 1.0),")
    lines.append("  new THREE.Color(0.5, 0.9, 0.4)")
    lines.append("];")
    lines.append("")
    lines.append("for (let t = 0; t < TENTACLE_COUNT; t++) {")
    lines.append("  const count = PARTICLES_PER_TENTACLE;")
    lines.append("  const positions = new Float32Array(count * 3);")
    lines.append("  const colors = new Float32Array(count * 3);")
    lines.append("  const sizes = new Float32Array(count);")
    lines.append("  const phases = new Float32Array(count);")
    lines.append("  for (let i = 0; i < count; i++) {")
    lines.append("    const theta = (t / TENTACLE_COUNT) * Math.PI * 2;")
    lines.append("    const r = 0.3 + (i / count) * 7.0;")
    lines.append("    const spread = 0.08 + (i / count) * 0.25;")
    lines.append("    positions[i*3] = Math.cos(theta) * r + (Math.random() - 0.5) * spread;")
    lines.append("    positions[i*3+1] = Math.sin(theta) * r + (Math.random() - 0.5) * spread;")
    lines.append("    positions[i*3+2] = (Math.random() - 0.5) * spread * 2;")
    lines.append("    const c = tentacleColors[t];")
    lines.append("    const fade = 0.2 + 0.8 * (1.0 - i / count);")
    lines.append("    colors[i*3] = c.r * fade;")
    lines.append("    colors[i*3+1] = c.g * fade;")
    lines.append("    colors[i*3+2] = c.b * fade;")
    lines.append("    sizes[i] = 0.04 + (1.0 - i / count) * 0.08;")
    lines.append("    phases[i] = Math.random() * Math.PI * 2;")
    lines.append("  }")
    lines.append("")
    lines.append("  const geometry = new THREE.BufferGeometry();")
    lines.append("  geometry.setAttribute('position', new THREE.BufferAttribute(positions, 3));")
    lines.append("  geometry.setAttribute('color', new THREE.BufferAttribute(colors, 3));")
    lines.append("  geometry.setAttribute('size', new THREE.BufferAttribute(sizes, 1));")
    lines.append("")
    lines.append("  const material = new THREE.PointsMaterial({")
    lines.append("    size: 0.08, vertexColors: true, transparent: true,")
    lines.append("    opacity: 0.85, blending: THREE.AdditiveBlending,")
    lines.append("    depthWrite: false, sizeAttenuation: true")
    lines.append("  });")
    lines.append("  const points = new THREE.Points(geometry, material);")
    lines.append("  scene.add(points);")
    lines.append("")
    lines.append("  tentacleGroups.push({")
    lines.append("    points, geometry, material,")
    lines.append("    basePositions: new Float32Array(positions),")
    lines.append("    phases, colors: tentacleColors[t],")
    lines.append("    theta: (t / TENTACLE_COUNT) * Math.PI * 2,")
    lines.append("    waveAmplitude: 0.4 + t * 0.05")
    lines.append("  });")
    lines.append("}")
    lines.append("")
    lines.append("// ---- Core glow (center) ----")
    lines.append("const glowGeo = new THREE.SphereGeometry(0.25, 16, 16);")
    lines.append("const glowMat = new THREE.MeshBasicMaterial({")
    lines.append("  color: new THREE.Color(0.4, 0.7, 1.0),")
    lines.append("  transparent: true, opacity: 0.8")
    lines.append("});")
    lines.append("const glowMesh = new THREE.Mesh(glowGeo, glowMat);")
    lines.append("scene.add(glowMesh);")
    lines.append("")
    lines.append("// ---- Background particles ----")
    lines.append("const bgParticleCount = 800;")
    lines.append("const bgPos = new Float32Array(bgParticleCount * 3);")
    lines.append("for (let i = 0; i < bgParticleCount * 3; i++) {")
    lines.append("  bgPos[i] = (Math.random() - 0.5) * 40;")
    lines.append("}")
    lines.append("const bgGeo = new THREE.BufferGeometry();")
    lines.append("bgGeo.setAttribute('position', new THREE.BufferAttribute(bgPos, 3));")
    lines.append("const bgMat = new THREE.PointsMaterial({")
    lines.append("  color: 0x446688, size: 0.03, transparent: true,")
    lines.append("  opacity: 0.3, blending: THREE.AdditiveBlending")
    lines.append("});")
    lines.append("const bgPoints = new THREE.Points(bgGeo, bgMat);")
    lines.append("scene.add(bgPoints);")
    lines.append("")
    lines.append("// ---- WS URL ----")
    lines.append("const WS_URL = 'ws://localhost:8000/ws';")
    lines.append("")
    lines.append("// ---- WebSocket ----")
    lines.append("let ws = null;")
    lines.append("let wsReconnectTimer = null;")
    lines.append("")
    lines.append("function connectWS() {")
    lines.append("  if (ws && ws.readyState <= WebSocket.OPEN) return;")
    lines.append("  try {")
    lines.append("    ws = new WebSocket(WS_URL);")
    lines.append("    ws.onopen = () => { console.log('WS connected'); setWudaoState('idle'); };")
    lines.append("    ws.onmessage = (e) => {")
    lines.append("      try {")
    lines.append("        const msg = JSON.parse(e.data);")
    lines.append("        if (msg.type === 'tentacle_state') {")
    lines.append("          console.log('tentacle_state:', msg.state);")
    lines.append("          setWudaoState(msg.state, msg.intensity || 0.5);")
    lines.append("        } else if (msg.type === 'partial_text') {")
    lines.append("          document.getElementById('transcript').innerHTML = '<span class=\"partial-text\">' + msg.text + '</span>';")
    lines.append("        } else if (msg.type === 'thinking_update') {")
    lines.append("          document.getElementById('status-text').textContent = '思考中';")
    lines.append("          setWudaoState('thinking');")
    lines.append("        } else if (msg.type === 'voice_result') {")
    lines.append("          document.getElementById('transcript').textContent = msg.text;")
    lines.append("          document.getElementById('status-text').textContent = '';")
    lines.append("        } else if (msg.type === 'message') {")
    lines.append("          document.getElementById('transcript').textContent = msg.text;")
    lines.append("        }")
    lines.append("      } catch(ex) {}")
    lines.append("    };")
    lines.append("    ws.onclose = () => {")
    lines.append("      console.log('WS closed, reconnecting in 3s');")
    lines.append("      setTimeout(connectWS, 3000);")
    lines.append("    };")
    lines.append("    ws.onerror = () => { console.log('WS error'); };")
    lines.append("  } catch(ex) {")
    lines.append("    console.log('WS connect failed, retry in 3s');")
    lines.append("    setTimeout(connectWS, 3000);")
    lines.append("  }")
    lines.append("}")
    lines.append("connectWS();")
    lines.append("")
    lines.append("// ---- setWudaoState ----")
    lines.append("window.setWudaoState = function(state, intensity) {")
    lines.append("  wudaoState = state;")
    lines.append("  const st = document.getElementById('status-text');")
    lines.append("  switch(state) {")
    lines.append("    case 'listening':")
    lines.append("      particleSpeed = 0.0005;")
    lines.append("      tentacleWaveSpeed = 0.0008;")
    lines.append("      bloomStrength = 0.25;")
    lines.append("      bloomPass.strength = 0.25;")
    lines.append("      st.textContent = '倾听中';")
    lines.append("      break;")
    lines.append("    case 'thinking':")
    lines.append("      particleSpeed = 0.008;")
    lines.append("      tentacleWaveSpeed = 0.012;")
    lines.append("      bloomStrength = 0.6;")
    lines.append("      bloomPass.strength = 0.6;")
    lines.append("      st.textContent = '思考中';")
    lines.append("      break;")
    lines.append("    case 'speaking':")
    lines.append("      speakIntensity = intensity || 0.5;")
    lines.append("      particleSpeed = 0.003 + speakIntensity * 0.008;")
    lines.append("      tentacleWaveSpeed = 0.004 + speakIntensity * 0.01;")
    lines.append("      bloomStrength = 0.35 + speakIntensity * 0.3;")
    lines.append("      bloomPass.strength = bloomStrength;")
    lines.append("      st.textContent = '';")
    lines.append("      break;")
    lines.append("    case 'idle':")
    lines.append("    default:")
    lines.append("      particleSpeed = 0.002;")
    lines.append("      tentacleWaveSpeed = 0.003;")
    lines.append("      bloomStrength = 0.4;")
    lines.append("      bloomPass.strength = 0.4;")
    lines.append("      st.textContent = '空闲';")
    lines.append("      break;")
    lines.append("  }")
    lines.append("};")
    lines.append("")
    lines.append("// ---- Speech Recognition ----")
    lines.append("let mediaRecorder = null;")
    lines.append("let audioChunks = [];")
    lines.append("let audioContext = null;")
    lines.append("let scriptProcessor = null;")
    lines.append("let micStream = null;")
    lines.append("let isRecording = false;")
    lines.append("")
    lines.append("document.addEventListener('keydown', (e) => {")
    lines.append("  if (e.key === ' ' && e.target === document.body) {")
    lines.append("    e.preventDefault();")
    lines.append("    if (!isRecording) { startRecording(); }")
    lines.append("  }")
    lines.append("});")
    lines.append("")
    lines.append("document.addEventListener('keyup', (e) => {")
    lines.append("  if (e.key === ' ' && isRecording) {")
    lines.append("    stopRecording();")
    lines.append("  }")
    lines.append("});")
    lines.append("")
    lines.append("async function startRecording() {")
    lines.append("  try {")
    lines.append("    isRecording = true;")
    lines.append("    setWudaoState('listening');")
    lines.append("    audioChunks = [];")
    lines.append("    if (ws && ws.readyState === WebSocket.OPEN) {")
    lines.append("      ws.send(JSON.stringify({ type: 'voice_start' }));")
    lines.append("    }")
    lines.append("    micStream = await navigator.mediaDevices.getUserMedia({ audio: {")
    lines.append("      sampleRate: 16000, channelCount: 1, echoCancellation: true")
    lines.append("    }});")
    lines.append("    audioContext = new AudioContext({ sampleRate: 16000 });")
    lines.append("    const source = audioContext.createMediaStreamSource(micStream);")
    lines.append("    scriptProcessor = audioContext.createScriptProcessor(2048, 1, 1);")
    lines.append("    source.connect(scriptProcessor);")
    lines.append("    scriptProcessor.connect(audioContext.destination);")
    lines.append("    scriptProcessor.onaudioprocess = (event) => {")
    lines.append("      if (!isRecording) return;")
    lines.append("      const input = event.inputBuffer.getChannelData(0);")
    lines.append("      const pcm16 = new Int16Array(input.length);")
    lines.append("      for (let i = 0; i < input.length; i++) {")
    lines.append("        pcm16[i] = Math.max(-32768, Math.min(32767, input[i] * 32768));")
    lines.append("      }")
    lines.append("      audioChunks.push(pcm16);")
    lines.append("      if (ws && ws.readyState === WebSocket.OPEN) {")
    lines.append("        const bytes = new Uint8Array(pcm16.buffer);")
    lines.append("        let binary = '';")
    lines.append("        for (let i = 0; i < bytes.length; i++) {")
    lines.append("          binary += String.fromCharCode(bytes[i]);")
    lines.append("        }")
    lines.append("        const b64 = btoa(binary);")
    lines.append("        ws.send(JSON.stringify({ type: 'voice_chunk', audio: b64 }));")
    lines.append("      }")
    lines.append("    };")
    lines.append("  } catch(ex) {")
    lines.append("    console.error('Mic error:', ex);")
    lines.append("    isRecording = false;")
    lines.append("  }")
    lines.append("}")
    lines.append("")
    lines.append("function stopRecording() {")
    lines.append("  isRecording = false;")
    lines.append("  if (scriptProcessor) {")
    lines.append("    scriptProcessor.disconnect();")
    lines.append("    scriptProcessor = null;")
    lines.append("  }")
    lines.append("  if (audioContext) {")
    lines.append("    audioContext.close();")
    lines.append("    audioContext = null;")
    lines.append("  }")
    lines.append("  if (micStream) {")
    lines.append("    micStream.getTracks().forEach(t => t.stop());")
    lines.append("    micStream = null;")
    lines.append("  }")
    lines.append("  if (ws && ws.readyState === WebSocket.OPEN) {")
    lines.append("    ws.send(JSON.stringify({ type: 'voice_end' }));")
    lines.append("  }")
    lines.append("  setWudaoState('idle');")
    lines.append("}")
    lines.append("")
    lines.append("// ---- Camera Reset ----")
    lines.append("let resetTimer = null;")
    lines.append("let isResetting = false;")
    lines.append("const DEFAULT_CAM_POS = new THREE.Vector3(0, 0, 12);")
    lines.append("const DEFAULT_TARGET = new THREE.Vector3(0, 0, 0);")
    lines.append("")
    lines.append("controls.addEventListener('end', () => {")
    lines.append("  if (resetTimer) clearTimeout(resetTimer);")
    lines.append("  resetTimer = setTimeout(() => {")
    lines.append("    isResetting = true;")
    lines.append("  }, 1000);")
    lines.append("});")
    lines.append("")
    lines.append("// ---- Animation loop ----")
    lines.append("const clock = new THREE.Clock();")
    lines.append("function animate() {")
    lines.append("  requestAnimationFrame(animate);")
    lines.append("  const time = clock.getElapsedTime();")
    lines.append("")
    lines.append("  // Animate tentacles")
    lines.append("  for (let t = 0; t < tentacleGroups.length; t++) {")
    lines.append("    const g = tentacleGroups[t];")
    lines.append("    const pos = g.geometry.attributes.position.array;")
    lines.append("    const count = pos.length / 3;")
    lines.append("    for (let i = 0; i < count; i++) {")
    lines.append("      const tNorm = i / count;")
    lines.append("      const radius = 0.3 + tNorm * 7.0;")
    lines.append("      const phase = g.phases[i];")
    lines.append("      const wave = Math.sin(time * tentacleWaveSpeed * 20 + phase) * g.waveAmplitude * tNorm * 0.3;")
    lines.append("      const wave2 = Math.cos(time * tentacleWaveSpeed * 15 + phase * 0.7) * g.waveAmplitude * tNorm * 0.15;")
    lines.append("      const theta = g.theta + wave * 0.005;")
    lines.append("      const spread = 0.08 + tNorm * 0.25;")
    lines.append("      pos[i*3] = Math.cos(theta) * radius + wave2 * 0.02;")
    lines.append("      pos[i*3+1] = Math.sin(theta) * radius + wave * 0.015;")
    lines.append("      pos[i*3+2] = wave * 0.01 + (Math.random() - 0.5) * spread * 0.01;")
    lines.append("    }")
    lines.append("    g.geometry.attributes.position.needsUpdate = true;")
    lines.append("  }")
    lines.append("")
    lines.append("  // Animate background particles")
    lines.append("  const bgPosArr = bgPoints.geometry.attributes.position.array;")
    lines.append("  for (let i = 0; i < bgPosArr.length; i += 3) {")
    lines.append("    bgPosArr[i+1] += particleSpeed;")
    lines.append("    if (bgPosArr[i+1] > 20) bgPosArr[i+1] = -20;")
    lines.append("  }")
    lines.append("  bgPoints.geometry.attributes.position.needsUpdate = true;")
    lines.append("")
    lines.append("  // Core glow pulse")
    lines.append("  glowMesh.scale.setScalar(1 + Math.sin(time * 0.5) * 0.1);")
    lines.append("  glowMesh.material.opacity = 0.6 + Math.sin(time * 0.3) * 0.2;")
    lines.append("")
    lines.append("  // Camera reset lerp")
    lines.append("  if (isResetting) {")
    lines.append("    const lerpSpeed = 0.03;")
    lines.append("    camera.position.lerp(DEFAULT_CAM_POS, lerpSpeed);")
    lines.append("    controls.target.lerp(DEFAULT_TARGET, lerpSpeed);")
    lines.append("    if (camera.position.distanceTo(DEFAULT_CAM_POS) < 0.01 &&")
    lines.append("        controls.target.distanceTo(DEFAULT_TARGET) < 0.01) {")
    lines.append("      camera.position.copy(DEFAULT_CAM_POS);")
    lines.append("      controls.target.copy(DEFAULT_TARGET);")
    lines.append("      isResetting = false;")
    lines.append("    }")
    lines.append("  }")
    lines.append("")
    lines.append("  controls.update();")
    lines.append("  composer.render();")
    lines.append("}")
    lines.append("animate();")
    lines.append("")
    lines.append("// ---- Resize handler ----")
    lines.append("window.addEventListener('resize', () => {")
    lines.append("  camera.aspect = window.innerWidth / window.innerHeight;")
    lines.append("  camera.updateProjectionMatrix();")
    lines.append("  renderer.setSize(window.innerWidth, window.innerHeight);")
    lines.append("  composer.setSize(window.innerWidth, window.innerHeight);")
    lines.append("});")
    lines.append("")
    lines.append("</script>")
    lines.append('</body>')
    lines.append('</html>')
    
    # Write with proper UTF-8 encoding
    output = '\n'.join(lines)
    with open('static/index.html', 'w', encoding='utf-8', newline='\r\n') as f:
        f.write(output)
    
    # Verify
    with open('static/index.html', 'rb') as f:
        raw = f.read()
    try:
        text = raw.decode('utf-8')
        print('UTF-8 decode: OK')
        print(f'File size: {len(raw)} bytes')
        # Check key features
        features = ['WS_URL', 'setWudaoState', 'startRecording', 'stopRecording',
                    'voice_start', 'voice_chunk', 'voice_end', 'OrbitControls', 'cameraReset']
        for feat in features:
            if feat in text:
                print(f'  [OK] {feat}')
            else:
                print(f'  [MISSING] {feat}')
        # Verify no garbled Chinese
        if '悟道' in text:
            print('  [OK] Title: 悟道')
        else:
            print('  [MISSING] Title: 悟道')
    except Exception as e:
        print(f'ENCODING ERROR: {e}')

if __name__ == '__main__':
    main()
